diana_soccer:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125  
  
  # Position Controllers ---------------------------------------
  # left leg ---------------------------------------
  l_hip_pitch_position:
    type: effort_controllers/JointPositionController
    joint: l_hip_pitch_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_hip_roll_position:
    type: effort_controllers/JointPositionController
    joint: l_hip_roll_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_hip_yaw_position:
    type: effort_controllers/JointPositionController
    joint: l_hip_yaw_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_knee_pitch_position:
    type: effort_controllers/JointPositionController
    joint: l_knee_pitch_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_ankle_pitch_position:
    type: effort_controllers/JointPositionController
    joint: l_ankle_pitch_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  l_ankle_roll_position:
    type: effort_controllers/JointPositionController
    joint: l_ankle_roll_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  # right leg ---------------------------------------
  r_hip_pitch_position:
    type: effort_controllers/JointPositionController
    joint: r_hip_pitch_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_hip_roll_position:
    type: effort_controllers/JointPositionController
    joint: r_hip_roll_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_hip_yaw_position:
    type: effort_controllers/JointPositionController
    joint: r_hip_yaw_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_knee_pitch_position:
    type: effort_controllers/JointPositionController
    joint: r_knee_pitch_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_ankle_pitch_position:
    type: effort_controllers/JointPositionController
    joint: r_ankle_pitch_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  r_ankle_roll_position:
    type: effort_controllers/JointPositionController
    joint: r_ankle_roll_joint
    pid: {p: 7500.0, i: 0.1, d: 100.0}

  # waist ---------------------------------------
  waist_roll_position:
    type: effort_controllers/JointPositionController
    joint: waist_roll_joint
    pid: {p: 350.0, i: 0.1, d: 100.0}

  waist_yaw_position:
    type: effort_controllers/JointPositionController
    joint: waist_yaw_joint
    pid: {p: 350.0, i: 0.1, d: 100.0}

  # left arm ---------------------------------------
  l_shoulder_pitch_position:
    type: effort_controllers/JointPositionController
    joint: l_shoulder_pitch_joint
    pid: {p: 350.0, i: 0.1, d: 100.0}

  l_shoulder_roll_position:
    type: effort_controllers/JointPositionController
    joint: l_shoulder_roll_joint
    pid: {p: 350.0, i: 0.1, d: 100.0}

  l_elbow_pitch_position:
    type: effort_controllers/JointPositionController
    joint: l_elbow_pitch_joint
    pid: {p: 350.0, i: 0.1, d: 100.0}

  # right arm ---------------------------------------
  r_shoulder_pitch_position:
    type: effort_controllers/JointPositionController
    joint: r_shoulder_pitch_joint
    pid: {p: 350.0, i: 0.1, d: 100.0}

  r_shoulder_roll_position:
    type: effort_controllers/JointPositionController
    joint: r_shoulder_roll_joint
    pid: {p: 350.0, i: 0.1, d: 100.0}

  r_elbow_pitch_position:
    type: effort_controllers/JointPositionController
    joint: r_elbow_pitch_joint
    pid: {p: 350.0, i: 0.1, d: 100.0}

  # head ---------------------------------------
  head_yaw_position:
    type: effort_controllers/JointPositionController
    joint: head_yaw_joint
    pid: {p: 350.0, i: 0.1, d: 100.0}

  head_pitch_position:
    type: effort_controllers/JointPositionController
    joint: head_pitch_joint
    pid: {p: 350.0, i: 0.1, d: 100.0}

  head_roll_position:
    type: effort_controllers/JointPositionController
    joint: head_roll_joint
    pid: {p: 350.0, i: 0.1, d: 100.0}



